apiVersion: v1
kind: Secret
metadata:
  name: memberlist
  namespace: metallb-system
stringData:
  secretkey: "me717oRd7UQapj1H7tTe+XaT5lMn/m0HZbn/Q3pNZLdNt8s8dvHhYAZkU1vdI+iA\nb6rtArNMQMPgxHpDNTgYeiOGV6S24T84ql3lEZRFraPSV/JpfushyeP/ZFZoX7Ad\n4i5Lel9OnqDPKdovwRioxelKWKLlp6JwzpOkIiGn0Yw="
